# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9T7l1QEdYJkSXPPNoBrzU_ZvUh2CAsg
"""

# Commented out IPython magic to ensure Python compatibility.
from sentence_transformers import SentenceTransformer
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline
model = SentenceTransformer("clip-ViT-B-32")

text_description = ["Two dogs in the snow ",
                    "A cat on a table ",
                    "A picture of london at night",
                    "Taj mahal view",
                    "A dog sleeping on a coach",
                    "Two cvats fighting in the garden"
                    "India's national parrot peacock"
                    "A beautiful pink rose"
                    "A beautiful green hills valley"]

def display_image_and_compare(image_path,text_discription):
  # loading image
  img = Image.open(image_path)

  # encode text and image (converting both into numbers)
  text_emb = model.encode(text_description)
  img_emb = model.encode(img)

  # compute similarity score
  similarity_score = np.dot(text_emb,img_emb)

  #find the best match
  best_match_index = np.argmax(similarity_score)
  best_match_desc = text_description[best_match_index]

  #print the final output
  print(f"\nBest match for the image is{best_match_desc} with score {similarity_score.max()}")

  # Display the iamge
  plt.figure(figsize = (6,6))
  plt.imshow(img)
  plt.axis("off")
  plt.title("Image for sismilarity comparsion",fontsize=14)
  plt.show()

text_description = "A beuatiful peacock"
display_image_and_compare("/content/6.jpg", text_description)

text_description = "A beautiful pink rose flower"
display_image_and_compare("/content/5.avif", text_description)

text_description = "A green beautiful green valley"
display_image_and_compare("/content/7.jfif", text_description)

